#!/bin/sh
make -s clean
make CC="x86_64-w64-mingw32-gcc -mconsole" || exit 1
mv -f asmx.exe asmx64.exe || exit 1
make -s clean
make CC="i686-w64-mingw32-gcc -mconsole" || exit 1
make -s clean
mv -f asmx.exe asmx64.exe .. || exit 1
echo "done"
ls -l ../*.exe
